#ifndef _BUTTON_DRIVER_H
#define _BUTTON_DRIVER_H

typedef enum {
  HANDBRAKE_BUTTON_UP,
  HANDBRAKE_BUTTON_DOWN,
  HANDBRAKE_BUTTON_MODE_TOGGLE,
  HANDBRAKE_BUTTON_NONE,
  HANDBRAKE_BUTTON_NUM
} HANDBRAKE_BUTTON;

HANDBRAKE_BUTTON get_handbrake_button();

#endif /* _BUTTON_DRIVER_H */